ARG VERSION='latest'
FROM opensearchproject/opensearch:$VERSION
# USER root
# RUN yum update -y
# RUN yum install -y unzip
# ADD https://github.com/opensearch-project/user-behavior-insights/releases/download/3.0.0.0/opensearch-ubi-3.0.0.0.zip /tmp/opensearch-ubi-3.0.0.0.zip
# RUN unzip -o /tmp/opensearch-ubi-3.0.0.0.zip -d opensearch-ubi
# USER 1000
# RUN /usr/share/opensearch/bin/opensearch-plugin install --batch query-insights
